config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # See how all your routes lay out with "bin/rails routes" or in the browser at "/routes".

  root to: 'welcome#index'
  get '/home' => 'weeks#index', as: 'home'

  resources :weeks, shallow: true do
    member do
      post 'enable'
      post 'disable'
      get 'render_week_plan'
    end

    resources :days do
      resources :shifts
    end
  end

  resources :shifts
  get 'my_shifts' => 'shifts#my_shifts'

  resources :shiftinfos

  resources :people do
    member do
      get 'find_location'
    end
  end

  get    '/signup' => 'people#new',       as: 'signup'
  get    '/login'  => 'sessions#new',     as: 'login'
  post   '/login'  => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  get '/help' => 'help#contact', as: 'help'

  namespace :tasks, path: 'sudo', as: nil do
    post 'cachesweep'
  end

end

app/models/week.rb
class Week < ApplicationRecord
  # Authorization plugin – Why?!?
  acts_as_authorizable; include AutHack

  has_many :days
  belongs_to :person, optional: true  #Wochenverantwortliche*r

  before_validation :assign_7_days, on: :create
  after_destroy :destroy_all_days

  validates_size_of    :days, is: 7, message: 'wrong_number_(expecting_{{count}})'
  validates_associated :days
  validates_presence_of     :number, on: :create
  validates_uniqueness_of   :number, on: :create
  validates_numericality_of :number, on: :create, only_integer: true, greater_than: 0, less_than_or_equal_to: 53

  # returns all days, monday first
  def weekdays
    days.sort_by{ |day| day.date }
  end

  def enabled?( saison )
    self.enabled_saisons.split(Week.enabled_saisons_delimiter).include? saison.id.to_s
  end
  def enable( saison )
    old = self.enabled_saisons.split(Week.enabled_saisons_delimiter)
    new = (old | [saison.id.to_s]).join(Week.enabled_saisons_delimiter)
    self.update_attribute(:enabled_saisons, new)
    self.all_shifts( saison ) { |shift| shift.enabled = true }
  end
  def disable( saison )
    old = self.enabled_saisons.split(Week.enabled_saisons_delimiter)
    new = (old - [saison.id.to_s]).join(Week.enabled_saisons_delimiter)
    self.update_attribute(:enabled_saisons, new)
    self.all_shifts( saison ) { |shift| shift.enabled = false }
  end
  def self.enabled_saisons_delimiter
    ','
  end


  protected

  def all_shifts( saison ) #expecting a block
    shifts = self.days.collect{|day| day.find_shifts_by_saison(saison)}.flatten
    shifts.each{ |shift| yield(shift) }
    shifts.all?(&:save)
  end


  private

  def assign_7_days
    return if days.present?

    year = Saison.first.begin.year
    logger.debug( "(II) Building 7 days for week #{self.number} in year #{year}:" )
    for cwday in 1..7
      @date = Date.commercial( year , self.number , cwday )
      logger.debug( "(II)   Day #{cwday}:  #{@date.strftime( "%d.%m." )}" )
      if Day.where(date: @date).exists?
        self.days << Day.find_by( date: @date )
      else
        self.days << Day.new( date: @date, week: self )
      end

    end
  end

  def destroy_all_days
    self.days.each(&:destroy)
  end

end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController

  before_action only: [:new, :create]  do |c| c.restrict_access 'webmaster' end
  before_action only: [:enable, :disable]  do |c| c.restrict_access 'admin' end
  # TODO: somehow prevent staff people from overwriting the inscription
  cache_sweeper :week_sweeper, only: [:enable, :disable, :edit, :update, :destroy]

  # GET /weeks
  # GET /weeks.xml
  def index
    @saisons = current_person.all_saisons_but_mine_first
    @weeks = Week.all.order(:number).includes(:days => {:shifts => {:shiftinfo => :saison}})
    past_year = @saisons.first.begin.year < Date.today.year
    @past_weeks, @future_weeks = @weeks.partition{ |w| past_year || w.number < Date.today.cweek }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @weeks }
    end
  end

  # GET /weeks/new
  # GET /weeks/new.xml
  def new
    @week = Week.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @week }
    end
  end

  # POST /weeks
  # POST /weeks.xml
  def create
    @week = Week.new(week_params)

    respond_to do |format|
      if @week.save
        flash[:notice] = t'weeks.create.success'
        format.html { redirect_to(@week) }
        format.xml  { render xml: @week, status: :created, location: @week }
      else
        format.html { render action: "new" }
        format.xml  { render xml: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /weeks/1
  # GET /weeks/1.xml
  def show
    @saisons = current_person.all_saisons_but_mine_first
    @week = Week.find(params[:id])

    if !fragment_exist? "#{@week.cache_key}_plans_#{current_person.roles_key_for_cache}"
      @days = @week.days.sort_by(&:date)
      @dd = WeeksHelper::WeekPlanDisplayData.for @week
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @week }
    end
  end

  # GET /weeks/1/edit
  def edit
    @saison = Saison.find_by name: "badi"  # TODO: SUPPORT MULTIPLE (>2) SAISONS
    @admin_names = Saison.admins_by_saison[@saison.name].collect(&:name)
    @week = Week.find(params[:id])
    @people = Person.all.order(:name).select{ |p| p.is_staff_for? @saison }
  end

  # PUT /weeks/1
  # PUT /weeks/1.xml
  def update
    @week = Week.find(params[:id])

    respond_to do |format|
      if @week.update(week_params)
        flash[:notice] = t'weeks.update.success'
        format.html { redirect_to(weeks_path) }
        #format.html { redirect_to(@week) }
        format.xml  { head :ok }
      else
        format.html { render action: "edit" }
        format.xml  { render xml: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1
  # DELETE /weeks/1.xml
  def destroy
    @week = Week.find(params[:id])
    @week.destroy()

    respond_to do |format|
      flash[:notice] = t'weeks.destroy.success'
      format.html { redirect_to(weeks_url) }
      format.xml  { head :ok }
    end
  end

  # GET /weeks/1/render_week_plan
  # TODO: replace by media-aware CSS
  def render_week_plan
    @saison = Saison.find(params[:saison_id])
    @week = Week.find(params[:id])
    @days = @week.days.sort_by(&:date)

    @dd = WeeksHelper::WeekPlanDisplayData.for @week
    @printout = true

    render( template: 'weeks/_week_plan', layout: 'popup', locals: {saison: @saison} )
  end

  # POST /weeks/1/enable
  def enable
    @week = Week.find(params[:id])
    @saison = Saison.find_by name: params[:saison_name]

    @week.enable(@saison)
    flash[:notice] = t 'weeks.enable.success', number: @week.number
    redirect_back_or_default(weeks_path)
  end

  # POST /weeks/1/disable
  def disable
    @week = Week.find(params[:id])
    @saison = Saison.find_by name: params[:saison_name]

    @week.disable(@saison)
    flash[:notice] = t 'weeks.disable.success', number: @week.number
    redirect_back_or_default(weeks_path)
  end


  private

  def week_params
    params.require(:week).permit!
  end

end

app/helpers/weeks_helper.rb
require 'memoist'

module WeeksHelper

  def phone_str( person, options = {} )
    options.reverse_merge! delimiter: ', '
    [person.phone, person.phone2].compact.reject(&:blank?).join(options[:delimiter]).html_safe
  end
  def day_td( day )
    tag.td(
      link_to( day.date.strftime( "%d.%m." ), day, style: "color:inherit;" ),
      day_td_html_options(day)
    )
  end
  def day_td_html_options( day )
    options = {
      class:       "weeks_table_td",
      onmouseover: "xstooltip_show('#{tooltip_id(day)}', '#{week_html_id(day.week)}', -8, -8);",
      onmouseout:  "xstooltip_hide('#{tooltip_id(day)}');"
    }

    if day.timely_active?
      options.merge style: "background: #{DayStyle.status_background(day.shifts)}, #eeeeee;"
    else
      options.merge style: "background: #e0e0e0; color: #ffffff;"
    end
  end
  def week_html_id( week )
    "week_#{week.number}"
  end
  def cell_link_to( text, target = {}, padding = "5px 3px" )
      link_to(
        tag.span(text, {style: "width: 100%; height: inherit; margin: #{padding};"}),
        target, {style: "width: #{WeekPlanDisplayData::DAY_WIDTH}px; height: inherit; display: table-cell; vertical-align: middle;", class: 'noprint'} )
  end


  class DayStyle

    def self.status_background( shifts )
      if shifts.any?
        colors = sorted_for_status_image(shifts).map{ |s| color_for_shift(s) }
        status_background_gradient(colors)
      else
        'none'
      end
    end

    def self.status_background_gradient( colors )
      target_height_px = 80
      target_gap_height_px = 1

      gap_height = 100.0 * target_gap_height_px / target_height_px
      remaining_height = 100.0 - (colors.length - 1) * gap_height
      bar_height = remaining_height / colors.length

      segments = []

      pos = 0.0
      colors.each.with_index do |color, idx|
        pos0 = pos
        pos1 = pos + bar_height
        pos2 = pos + bar_height + gap_height
        pos = pos2

        bar_from_to = [color, pos0, pos1]
        segments << bar_from_to

        unless idx == colors.length - 1
          gap_from_to = ['transparent', pos1, pos2]
          segments << gap_from_to
        end
      end

      segments = segments.reduce([]) do |segments_dedup, s2|
        if segments_dedup.none?
          [s2]
        else
          s1 = segments_dedup.pop
          color1, from1, _to1 = s1
          color2, _from2, to2 = s2
          if color1 == color2
            segments_dedup << [color1, from1, to2]
          else
            segments_dedup << s1 << s2
          end
        end
      end

      segments = segments.flat_map{ |(color, posA, posB)| [[color, posA], [color, posB]] }
      segments = segments[1..-2] if segments.length > 2

      "linear-gradient(to bottom, #{segments.map{ |s| '%s %.1f%%' % s }.join(", ")})"
    end

    def self.color_for_shift(shift)
      case [shift.saison.name, shift.status]
      when [Saison.badi.name,  :taken   ] then 'transparent'
      when [Saison.badi.name,  :free    ] then 'rgba( 38, 158, 0, 0.6)'
      when [Saison.badi.name,  :disabled] then 'rgba( 38, 158, 0, 0.3)'
      when [Saison.kiosk.name, :taken   ] then 'transparent'
      when [Saison.kiosk.name, :free    ] then 'rgba(255, 255, 0, 0.6)'
      when [Saison.kiosk.name, :disabled] then 'rgba(255, 255, 0, 0.3)'
      else 'red'
      end
    end

    def self.sorted_for_status_image(shifts)
      shifts.sort_by{ |s| [s.shiftinfo.saison_id, s.shiftinfo.begin_plus_offset] }
    end

  end


  class WeekPlanDisplayData
    extend Memoist

    HOUR_HEIGHT   = 30
    HEADER_HEIGHT = 35
    DAY_WIDTH     = 125
    TIME_HEIGHT   = 20  #css: height=17px + border=2*1px
    TIME_WIDTH    = 50 + 5

    attr_accessor :week


    def self.for( week )
      instance = new
      instance.week = week
      return instance
    end

    def h_offset( cwday )
      index = cwday - 1  # Monday..Sunday -> 0..6
      h_offset_day_count(index)
    end
    def h_offset_times
      {
        left:  0,
        right: h_offset_day_count(7)
      }
    end
    memoize :h_offset, :h_offset_times

    def style_for_wnum
      "float:       left;
       font-size:   75px;
       line-height:  1em;
       margin:      -8px 16px 3px 3px;"
    end
    def style_for_day( saison )
      "position: relative;
       height:   #{HEADER_HEIGHT + day_height(saison)}px;
       margin:   2em 0em;"
    end
    def style_for_day_header( day )
      "position: absolute;
       left:     #{h_offset(day.date.cwday)}px;
       width:    #{DAY_WIDTH}px;
       top:      0px;
       height:   #{HEADER_HEIGHT - 3}px;
       text-align: center;"
    end
    def style_for_day_body( day )
      "position: absolute;
       left:     #{h_offset(day.date.cwday)}px;
       width:    #{DAY_WIDTH}px;
       top:      #{HEADER_HEIGHT}px; "
    end
    def style_for_shift( shift )
      si = shift.shiftinfo
      v_offset = v_offset_begin(si)

      top    = v_offset                    - 1 #border
      height = time2pixels(shift.duration) - 1 #border
      bg_color = shift.free? ? shift.saison.color : "#eeeeee"

      "top:        #{top}px;
       height:     #{height}px;
       background: #{bg_color};"
    end


    def times( saison, side )
      shifts_by(saison, side).map do |shift|
        si = shift.shiftinfo
        begin_top  = HEADER_HEIGHT + v_offset_begin(si) - 1
        end_top    = HEADER_HEIGHT + v_offset_end(si) - TIME_HEIGHT
        [si.begin, begin_top, si.end, end_top]
      end
    end
    def shifts_by( saison, side )
      day = case side
            when :left  then week.days.first
            when :right then week.days.last
            else raise('No such side. Use :left or :right.')
            end
      day.find_shifts_by_saison(saison)
    end
    memoize :times, :shifts_by

    def day_height( saison )
      shiftinfos = Shiftinfo.for_week_and_saison(week, saison)
      min = earliest_second(shiftinfos)
      max = latest_second(shiftinfos)
      time2pixels(max - min)
    end
    memoize :day_height


    # Disable the default constructor.
    private_class_method :new

    private

    def time2pixels( seconds )
      (HOUR_HEIGHT * seconds.to_f/1.hour.to_f).round
    end

    def h_offset_day_count( number_of_days )
      TIME_WIDTH + number_of_days * (DAY_WIDTH + 5)
    end

    def v_offset_begin( shiftinfo )
      v_offset(shiftinfo.saison, shiftinfo.begin_plus_offset)
    end
    def v_offset_end( shiftinfo )
      v_offset(shiftinfo.saison, shiftinfo.end_plus_offset)
    end
    def v_offset( saison, time_in_seconds )
      shiftinfos = Shiftinfo.for_week_and_saison(week, saison)
      time2pixels(time_in_seconds - earliest_second(shiftinfos))
    end

    def earliest_second(shiftinfos)
      shiftinfos.map(&:begin_plus_offset).min
    end
    def latest_second(shiftinfos)
      shiftinfos.map(&:end_plus_offset).max
    end
    memoize :earliest_second, :latest_second

  end
end

app/views/weeks/_week_jumper.html.erb
<% before = Week.find_by number: @week.number - 1 %>
<% after  = Week.find_by number: @week.number + 1 %>

<div class="week_jumper noprint">
  <%= link_to_unless( before.nil?, "←", before ) %>

  <% for week in Week.all.order(:number) %>
    <%= link_to_unless_current( tag.span(week.number ), week, class: "jumplink" )%>
  <% end %>

<%= link_to_unless( after.nil?, "→", after ) %>
</div>

app/views/weeks/_week_plan.html.erb
<span id="week_plan">
  <span style="<%= @dd.style_for_wnum %>"> <%= @week.number.to_s if @printout %> </span>

  <h2 style="margin-bottom: 5px;">
    <%=t( 'weeks.week_plan.caption',
          begin_date: h(@days.first.date_str "%d.%m."),
          end_date: h(@days.last.date_str "%d.%m.%Y"))%>
  </h2>

  <%= if saison.name.eql? "badi"; render( partial: 'week_plan_responsability', locals: {saison: saison} ); end %>

  <% @days.each do |day| %>
    <% unless content_for?("day_header_#{day.date.cwday}") %>
    <% content_for "day_header_#{day.date.cwday}" do %>
      <span style="float: left;  padding-left:  5px; font-size:   1.6em;"><%= day.date_str('%a') %></span>
      <span style="float: right; padding-right: 5px; padding-top: 0.5em;"><%= day.date_str('%d.%m.') %></span>
    <% end %>
    <% end %>
  <% end %>

  <div style="<%= @dd.style_for_day( saison ) %>">
    <%= render( partial: 'week_plan_times', locals: { saison: saison, side: :left } )%>
    <%= render( partial: 'week_plan_day',   locals: { saison: saison }, collection: @days, as: :day )%>
    <%= render( partial: 'week_plan_times', locals: { saison: saison, side: :right } )%>
  </div>

  <% if @printout %>
  <div><p><%=t 'weeks.week_plan.badi_tel' %></p></div>
  <% end %>
</span>

app/views/weeks/_week_plan_day.html.erb
<span style="<%= @dd.style_for_day_header(day) %>">
  <%= link_to_unless( @printout,
                      content_for("day_header_#{day.date.cwday}"),
                      day,
                      {title: t('days.show.title', date_str: day.date_str), class: "block"} ) %>
</span>

<span style="<%= @dd.style_for_day_body(day) %>">
	<%= render( partial: 'week_plan_shift',
              collection: day.find_shifts_by_saison(saison), as: :shift,
              locals: { saison: saison } )%>
</span>

app/views/weeks/_week_plan_responsability.html.erb
<%=t 'weeks.responsability' %>:

<% if @week.person.nil? %>
  <% if current_person.is_admin_for?(saison) or (current_person.is_staff_for?(saison) and @week.enabled?(saison)) %>
    <%= link_to( t('weeks.sign_up'), edit_week_path(@week) ) %>
  <% else %>
    vakant
  <% end unless @printout %>
<% else %>
  <span style="font-size: larger;"><%= @week.person.name %></span>
  <% if @printout %>
    <br /><%= t('phone_short') %>: <%= phone_str(@week.person) %>
  <% end %>
<% end %>

app/views/weeks/_week_plan_shift.html.erb
<span class="week_plan_shift" style="<%= @dd.style_for_shift(shift) %>">

  <span>
    <% if shift.free? %>
      <% unless @printout %>

        <% if current_person.is_admin_for?(saison) %>
          <%= cell_link_to( t('shifts.sign_up'), day_path(shift.day) ) %>
        <% elsif current_person.is_staff_for?(saison) and shift.can_staff_sign_up? %>
          <%= cell_link_to( t('shifts.sign_up'), edit_shift_path(shift) ) %>
        <% else %>
          <p class="inscribed_person vacancy noprint">vakant</p>
        <% end %>

      <% end %>
    <% else %>
      <p class="inscribed_person">
        <span class="person_name"><%= shift.person.name %></span><br />
        <span class="person_phone_numbers"><%= phone_str(shift.person, delimiter: '<br />') %></span>
      </p>
    <% end %>
  </span>

  <%= image_tag_brevet if shift.person && shift.person.brevet? %>

</span>

app/views/weeks/_weeks_past_view.erb
<h3><%=t 'weeks.past_weeks' %>:</h3>
<div class="week_jumper">
	<% for week in @past_weeks %>
		<%= link_to_unless_current( tag.span(week.number ), week, class: "jumplink" )%>
  <% end %>
</div>

app/views/weeks/_weeks_table.html.erb
<noscript><%= tag.div(t('noscript'), class: "flash", id: "flash_noscript") -%></noscript>

<table class="weeks_table">
  <thead>
    <tr>
      <th class="weeknum_header" style="padding-right: 1em;"><em><%=t 'weeks.weeks_table.weeknum_header' %></em></th>
      <% for cwday in 1..7 %>
        <th class="day_header"><%= t('date.abbr_day_names')[cwday % 7] %></th>
      <% end %>
      <th> <%=t 'weeks.responsability' %> </th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "weeks_table_row", collection: @future_weeks, as: :week %>
  </tbody>
</table>

<span id="day_tooltips">
<% for week in @future_weeks %>
  <% cache( "#{week.cache_key}_tooltips_#{current_person.roles_key_for_cache}" ) do %>

    <% for day in week.days %>
      <%= tooltip_div(day) if day.timely_active? %>
    <% end %>

  <% end %>
<% end %>
</span>

app/views/weeks/_weeks_table_cell.html.erb
<%= day_td(day) %>

app/views/weeks/_weeks_table_row.html.erb
<% cache( "#{week.cache_key}_row_#{current_person.roles_key_for_cache}" ) do %>

  <tr id="<%= week_html_id(week) %>">
    <th style="padding-right: 1em;">
      <em class="week_number"><%= link_to( week.number, week, title: t('weeks.show.title') )%></em>
      <% for saison in current_person.is_admin_for_what %>
        <br /><%= week.enabled?(saison) ?
                    link_to('Deaktivieren', disable_week_path(week, saison_name: saison.name), style: "color: #{saison.color}", method: :post ) :
                    link_to(  'Aktivieren', enable_week_path(week, saison_name: saison.name), style: "color: #{saison.color}", method: :post )  %>
      <% end %>
    </th>

    <%= render( partial: 'weeks_table_cell', collection: week.weekdays, as: :day ) %>

    <% if !!week.person %>
      <td>
        <%= week.person.name %><br />
        <%= week.person.phone %><br />
        <%= link_to( t('Edit'), edit_week_path(week) ) if current_person.is_admin_for? Saison.find_by(name: 'badi') %>
      </td>
    <% elsif current_person.is_admin_for? Saison.badi or (current_person.is_staff_for? Saison.badi and week.enabled?(Saison.badi)) %>
      <td> frei <br /><%= link_to( ' ' + t('weeks.sign_up') + ' ' , edit_week_path(week) ) %></td>
    <% else %>
      <td> vakant </td>
    <% end %>
  </tr>

<% end %>

app/views/weeks/_weeks_table_tr.html.erb
<tr id="<%= week_html_id(week) %>">
  <th style="padding-right: 1em;">
    <em class="week_number"><%= link_to( week.number, week, :title => t('weeks.show.title') )%></em>
    <% for saison in current_person.is_admin_for_what %>
      <br /><%= week.enabled?(saison) ?
                  link_to('Deaktivieren', week_disable_path(week, saison.name), :style => "color: #{saison.color}" ) :
                  link_to(  'Aktivieren', week_enable_path(week, saison.name), :style => "color: #{saison.color}" )  %>
    <%# elsif current_person.is_webmaster? %>
      <%#<br /><%= link_to( t('Delete'), week, :confirm => t('weeks.confirm_delete'), :method => :delete )%>
    <% end %>
  </th>

  <%= render( :partial => 'weeks_table_td', :collection => week.weekdays, :as => :day ) %>

  <% if !!week.person %>
    <td>
      <%=h week.person.name %><br />
      <%=h week.person.phone %><br />
      <%= link_to( t('Edit'), edit_week_path(week) ) if current_person.is_admin_for? Saison.find_by_name('badi') %>
    </td>
  <% elsif current_person.is_staff_for? Saison.badi and week.enabled?(Saison.badi) %>
    <td> frei <br /><%= link_to( ' ' + t('weeks.sign_up') + ' ' , edit_week_path(week) ) %></td>
  <% else %>
    <td> vakant </td>
  <% end %>
</tr>

app/views/weeks/edit.html.erb
<% content_for :title, @title = t('weeks.edit.title') %>
<% content_for :navigation_links do %>
  <%= navigation_link( t('weeks.show.title'), @week )%>
<% end %>


<%= form_with model: @week do |f| %>
  <p>
    <% if current_person.has_role? 'admin' %>
      <b><%=t 'weeks.responsability' %>:</b><br />
      <%= f.select( :person_id, @people.collect {|p| [ p.name, p.id ] }, { include_blank: true } ) %>
    <% else %>
      <h2><%= t('weeks.edit.general_advice', wnum: @week.number.to_s ) %></h2>
      <%= f.hidden_field :person_id, value: current_person.id %>
    <% end %>
  </p>

  <p>
    <%= f.submit t('Save') %><br />
  </p>
<% end %>
<p><%= link_to( t('Abort'), :weeks ) %></p>

<% unless current_person.has_role? 'admin'  %>
  <p><em>
      <%= t('weeks.edit.warning', admin_names: @admin_names.join(" #{t('or')} ")).html_safe %><br />
      <%= link_to( t('help.contact.title') , controller: 'help', action: 'contact' )%><br />
      <br />
      <%=t 'abort_with_backbutton' %>
  </em></p>
<% end %>

app/views/weeks/index.html.erb
<% content_for :title, @title = t('weeks.index.title') %>
<% content_for :dynamic_links_for_webmaster do %>
  <%#= navigation_link t('weeks.new.title'), new_week_path %>
  <%= navigation_link t('cache.sweep.title'), cachesweep_path, method: :post %>
<% end %>


<%= render( partial: 'weeks_table' )     unless @future_weeks.none? %>

<%= render( partial: 'weeks_past_view' ) unless @past_weeks.none?  %>

app/views/weeks/new.html.erb
<% content_for :title, @title = t('weeks.new.title') %>


<%= render( 'shared/error_messages', obj: @week ) %>

<%=t 'weeks.new.taken_numbers' %>: <%= Week.all.collect(&:number).sort.join(', ') %>

<%= form_with model: @week do |f| %>
  <p>
    <b><%=t 'weeks.new.week_number_label' %></b><br />
    <%= f.text_field :number %>
  </p>

  <p>
    <%= f.submit t('Save') %>
  </p>
<% end %>

app/views/weeks/show.html.erb
<% content_for( :title, t('weeks.week_plan.title', wnum: @week.number) )%>
<% content_for :dynamic_links_for_admin do %>
  <%= navigation_link t('weeks.new.title'), new_week_path %>
<% end %>

<% cache( "#{@week.cache_key}_plans_#{current_person.roles_key_for_cache}" ) do %>

  <%= render( partial: 'week_jumper' )%>

  <% for @saison in @saisons %>

    <% if @saisons.many? %>
      <h2><%=t "saisons.#{@saison.name}" %></h2>
    <% end %>

    <%= render( partial: 'week_plan', locals: {saison: @saison} )%>
    
    <%= link_to( t('weeks.show.printout'),
      { action: "render_week_plan", id: @week, saison_id: @saison },
      { class: 'noprint', popup: true } )%>
      
    <h2><br /></h2>

  <% end %>

<% end %>