config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # See how all your routes lay out with "bin/rails routes" or in the browser at "/routes".

  root to: 'welcome#index'
  get '/home' => 'weeks#index', as: 'home'

  resources :weeks, shallow: true do
    member do
      post 'enable'
      post 'disable'
      get 'render_week_plan'
    end

    resources :days do
      resources :shifts
    end
  end

  resources :shifts
  get 'my_shifts' => 'shifts#my_shifts'

  resources :shiftinfos

  resources :people do
    member do
      get 'find_location'
    end
  end

  get    '/signup' => 'people#new',       as: 'signup'
  get    '/login'  => 'sessions#new',     as: 'login'
  post   '/login'  => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  get '/help' => 'help#contact', as: 'help'

  namespace :tasks, path: 'sudo', as: nil do
    post 'cachesweep'
  end

end

app/models/person.rb
require 'digest/sha1'
class Person < ApplicationRecord
  REMEMBER_ME_TIME = 1.hour

  has_many :people_roles
  has_many :roles, through: :people_roles
  scope :having_role, -> (role_name) { joins(:roles).merge(Role.where(name: role_name)) }

  # Authorization plugin
  acts_as_authorized_user
  acts_as_authorizable; include AutHack

  has_many :shifts
  has_many :weeks  #als Wochenverantwortliche/r

  before_save :encrypt_password
  after_destroy :free_all_shifts

  validates_uniqueness_of   :name, :login, case_sensitive: false
  validates_presence_of     :name, :login, :phone
  validates_presence_of     :password,                if: :password_required?
  validates_presence_of     :password_confirmation,   if: :password_required?
  validates_confirmation_of :password,                if: :password_required?
  validates_length_of       :password, within: 4..40, if: :password_required?
  validates_length_of       :name,     within: 3..50
  validates_length_of       :login,    within: 3..20
  validates_length_of       :email,    maximum: 100,                                      allow_blank: true
  validates_length_of       :address,  maximum:  50,                                      allow_blank: true
  validates_length_of       :location, maximum:  30,                                      allow_blank: true
  validates_format_of       :postal_code, with: /\A([1-9][0-9]{3})\Z/,                    allow_blank: true, message: I18n.translate('person.invalid_zip')
  validates_format_of       :phone,  with: /\A(0[1-9]{2} [0-9]{3} [0-9]{2} [0-9]{2})\Z/i, allow_blank: true, message: I18n.translate('person.invalid_phone')
  validates_format_of       :phone2, with: /\A(0[1-9]{2} [0-9]{3} [0-9]{2} [0-9]{2})\Z/i, allow_blank: true, message: I18n.translate('person.invalid_phone')

  # Uses Carsten Nielsen's email_veracity gem (see lib/EmailVeracityValidator.rb)
  validates :email, email_veracity: true

  # Virtual attribute for the unencrypted password
  attr_accessor :password

  def full_address_str( options = {} )
    options.reverse_merge! delimiter: ', '
    str = ''
    str << address unless !address  # must append instead of a direct assignment in order to get a copy
    str << (str.blank? ? '' : options[:delimiter]) + postal_code.to_s if postal_code
    str << (str.blank? ? '' : ' ') + location if location
    return str.html_safe
  end

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  def self.authenticate(login, password)
    u = find_by login: login # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  # Encrypts some data with the salt.
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  # Encrypts the password with the user salt
  def encrypt(password)
    self.class.encrypt(password, salt)
  end

  def authenticated?(password)
    #(RAILS_ENV == 'production')^(name =~ /test\d/) and
    crypted_password == encrypt(password)
  end

  def remember_token?
    remember_token_expires_at && Time.now.utc < remember_token_expires_at
  end

  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    remember_me_for REMEMBER_ME_TIME
  end

  def remember_me_for(time)
    remember_me_until time.from_now.utc
  end

  def remember_me_until(time)
    self.remember_token_expires_at = time
    self.remember_token            = encrypt("#{email}--#{remember_token_expires_at}")
    save(validate: false)
  end

  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token            = nil
    save(validate: false)
  end

  # Returns true if the user has just been activated.
  def recently_activated?
    @activated
  end

  def administrates?( person )
    is_admin? or is_webmaster?
  end

  def roles_str
    self.roles.collect{ |role| role.translate }.to_sentence
  end
  def roles_key_for_cache
    keys = Array.new
    Saison.all.each{ |saison|
      keys << saison.name.chars.first.upcase   if self.is_admin_for?( saison )
      keys << saison.name.chars.first.downcase if self.is_staff_for?( saison )
    }
    keys << 'w' if self.is_webmaster?
    keys.sort.join
  end

  def my_saisons
    self.roles.includes(:authorizable).collect(&:authorizable).flatten.uniq.compact.sort_by(&:name)
  end
  def all_saisons_but_mine_first
    my_saisons | Saison.all.order(:name)
  end
  def unrelated_saisons
    Saison.all.order(:name) - my_saisons
  end
  def admin_saisons
    is_admin_for_what.sort_by(&:name)
  end
  def non_admin_saisons
    (is_staff_for_what - is_admin_for_what) | unrelated_saisons
  end

  def self.find_by_role role_name
    roles = Role.where(name: role_name).includes(:people)
    roles.collect{ |role| role.people }.flatten.uniq.sort_by(&:name)
  end

  protected
    # before filter
    def encrypt_password
      return if password.blank?
      self.salt = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{login}--") if new_record?
      self.crypted_password = encrypt(password)
    end

    def password_required?
      crypted_password.blank? || !password.blank?
    end

  private
    def free_all_shifts
      self.shifts.each {| shift | shift.forget_person! }
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  # Do not allow anyone to subscribe by themselves
  #skip_before_action :login_required, only: [:new, :create]
  before_action only: [:new, :create, :destroy] do |c| c.restrict_access ['admin', 'webmaster'] end

  # GET /people
  def index
    @people = Person.order('name')

    @csv_attributes = %w[ name address postal_code location phone phone2 email preferences roles_str brevet ]
    @csv_delimiter  = ';'
  end

  # GET /people/new
  def new
    @person = Person.new()
  end

  # POST /people/create
  def create
    cookies.delete :auth_token
    # protects against session fixation attacks, wreaks havoc with request forgery protection.
    # uncomment at your own risk
    # reset_session
    @person = Person.new(person_params)
    update_staff_roles(@person)
    if @person.save
      flash[:notice] = t'people.create.success'
      self.current_person = @person unless logged_in? # admin can create people without losing his login
      redirect_back_or_default(people_path)
    else
      render action: 'new'
    end
  end

  def destroy
    @person = Person.find(params[:id])

    if @person.is_webmaster?
      flash[:error] = t'people.destroy.webmaster_cannot_be_deleted_by_admin'
    else
      @person.destroy
      flash[:notice] = t('people.destroy.success', person_name: @person.name)
    end

    redirect_back_or_default(people_path)
  end

  # GET /shiftinfos/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # PUT /people/1
  def update
    @person = Person.find(params[:id])
    update_staff_roles(@person)
    if @person.update(person_params)
      flash[:notice] = t'people.update.success'
      render action: "edit" #pointing there on purpose
    else
      render action: "edit"
    end
  end

  # GET /people/find_location  (used in ajax call)
  def find_location
    @location = PeopleHelper.fetch_location_by_postal_code(params[:zip])

    if @location.blank?
      render nothing: true
    else
      render :update do |page|
        page["person_location"].setValue( @location )
      end
    end
  end

  # PUT /people/1/set_roles
  # What is this method good for?
#  def act_as_various # TODO: make GUI
#    current_person.is_webmaster? || redirect_to( login_path ) and return false
#    render :update do
#      for role in "badiAdmin badiStaff kioskAdmin kioskStaff".split(' ') # TODO: automatically find all by DOM
#        if page["toggle_"+role].value
#          current_person.has_role role
#        else
#          current_person.has_no_role role
#        end
#      end
#    end
#  end


  private

  def staff_roles
    Role.where(name: 'staff').order(:id)
  end
  helper_method :staff_roles

  def update_staff_roles(person)
    staff_role_ids = staff_roles.map{ |r| r.id.to_s }
    role_ids = person.role_ids.map(&:to_s)

    role_params.each do |role_id, checked|
      if staff_role_ids.include?(role_id)
        if checked == '1'
          role_ids << role_id unless role_ids.include? role_id
        else
          role_ids.delete role_id
        end
      end
    end

    person.role_ids = role_ids
  end

  def person_params
    params[:person] ||= {}
    params[:person].permit(
        :name, :login, :phone, :phone2, :address, :postal_code, :location,
        :email, :preferences, :password, :password_confirmation, :brevet
    )
  end

  def role_params
    params[:person] ||= {}
    params[:person][:roles] || {}
  end

end

app/helpers/people_helper.rb
module PeopleHelper
  require 'net/http'

  def person_select_label( person )
    person_with_brevet(person)
  end

  def person_with_brevet(person)
    label = h person.name
    label << ' [B]' if person.brevet?
    label
  end

  def image_tag_brevet
    image_tag asset_path('brevet.jpg'), class: 'brevet', alt: '[B]', title: 'Hat ein Brevet'
  end

  def render_people_list( title, people )
    render( partial: 'list_people',
            locals: {
              title: title,
              people: people } )
  end

  def self.fetch_location_by_postal_code(zip)
    return nil unless zip.to_s.size == 4
    begin
      timeout(0.5) do
        response = Net::HTTP.get_response("map.search.ch", zip.to_s )
        puts response.to_yaml
        return response.is_a?(Net::HTTPMovedPermanently) ? capitalized_location(response, zip.to_s) : nil
      end
    rescue TimeoutError
      Person.logger.warn("Timeout accessing http://map.search.ch/#{zip.to_s}: '#{$!}'  - Not updating the location field.")
      return nil
    end
  end

  private
  def self.capitalized_location(http_response, exclude="")
    location = http_response['location'].split('/').last # e.g. "bueren-zum-hof"
    if location == "map.search.ch"
      return nil
    else
      parts = location.split('-').reject {|part| part == exclude}
      parts.first.capitalize!
      parts.last.capitalize!
      location = parts.join(' ');                        # e.g. "Bueren zum Hof"
    end
  end

end

app/views/people/_address_link_if_complete.html.erb
<% if !!person.postal_code and !person.address.blank? %>
	<%= link_to( person.full_address_str(delimiter: '<br />'), "http://map.search.ch/#{person.postal_code}/#{person.address.untaint}",
							 title: t('people.show_map'), popup: true )%>
<% else %>
	<%= person.full_address_str %>
<% end %>

app/views/people/_person_form.html.erb
<%= render( 'shared/error_messages', obj: @person ) %>

<%= form_with model: @person do |f| %><div>

  <!-- This should soak up the browser's password autocomplete attempts -->
  <input type="password" style="display: none;" readonly />

  <div style="float: left; margin-right: 2em;">

    <p><label for="person_name"><%=t 'person.attributes.name' %></label><br />
		<%= f.text_field( :name )%></p>

		<p><label for="person_address"><%=t 'person.attributes.address' %></label><br />
		<%= f.text_field( :address )%></p>

		<p><label for="person_postal_code"><%=t 'person.attributes.postal_code' %></label>/<label for="location"><%=t 'person.attributes.location' %></label><br />
		<%= f.text_field( :postal_code, size:  5 )%>
		<span id="location_field_container"><%= f.text_field( :location, size: 21 )%></span></p>

	</div>
  <div style="float: left; margin-right: 2em;">

		<p><label for="person_login"><%=t 'person.attributes.login' %></label><br />
		<%= f.text_field( :login )%></p>

		<p><label for="person_email"><%=t 'person.attributes.email' %></label><br />
		<%= f.text_field( :email )%></p>

    <p><label for="person_phone"><%=t 'person.attributes.phone' %></label><br />
    <%= f.text_field( :phone )%></p>

    <p><label for="person_phone2"><%=t 'person.attributes.phone2' %></label><br />
    <%= f.text_field( :phone2 )%></p>

  </div>
  <div style="float: left; margin-right: 2em;">

    <p><label for="password"><%=t 'people.password_label' %></label><br/>
      <%= f.password_field( :password, autocomplete: "off" )%></p>

    <p><label for="password_confirmation"><%=t 'people.password_confirmation_label' %></label><br/>
      <%= f.password_field( :password_confirmation )%></p>

  </div>

  <% if current_person.has_role? 'admin' or current_person.has_role? 'webmaster' %>
    <div style="float: left; margin-right: 2em;">
      <p><label for="person_preferences"><%=t 'people.preferences_label' %></label><br />
        <%= f.text_field( :preferences, rows: 4, size: 67 )%></p>

      <p><%= t 'people.skills_label' %><br />
        <%= f.check_box(:brevet) %>
        <label for="person_brevet"><%= t 'person.attributes.brevet' %></label>
      </p>

      <label for="roles"><%= t 'role.n' %></label>
      <ul class="checkboxes">
        <% staff_roles.each do |role| %>
          <%= f.fields_for :roles, role do |roles_form| %>
            <li>
              <%= roles_form.check_box(role.id, checked: @person.roles.include?(role)) %>
              <label for="person_roles_<%= role.id %>"><%= role.translate %></label>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="clear: left;">

		<p><%= submit_tag( t'Save' )%>
		<em> <%=t 'save_button_remark' %> </em></p>

	</div>
</div><% end %>

app/views/people/edit.html.erb
<% content_for( :title, @title = t('people.edit.title.admin') )%>

<p><%= render( partial: 'person_form', locals: { person: @person } ) %></p>

app/views/people/index.csv.erb
<%= @csv_attributes.map{|attr| Person.human_attribute_name attr}.join(@csv_delimiter) %>
<% for person in @people.select{|person| current_person.administrates? person} %>
<%= @csv_attributes.map{|attr| person.__send__ attr}.join(@csv_delimiter) %>
<% end %>

app/views/people/index.html.erb
<% content_for :title, @title = t('people.index.title') %>
<% content_for :additional_formats, "csv" if current_person.has_role? 'admin' %>
<% content_for :dynamic_links_for_admin do %>
  <%= navigation_link t('people.create.title'), new_person_path %>
<% end %>
<% content_for :dynamic_links_for_webmaster do %>
  <%= navigation_link t('people.create.title'), new_person_path %>
<% end %>

<table id="people_list">
  <tr>
    <th></th>
    <th><%=t 'person.attributes.name' %></th>
<% if current_person.has_role? 'admin' %>
  	<th>#<%=t 'assignments' %></th>
    <th><%=t 'person.attributes.preferences' %></th>
<% end %>
    <th><%=t 'person.attributes.phone' %></th>
    <th><%=t 'person.attributes.address' %></th>
  </tr>

<% for person in @people %>
  <tr class="<%= cycle('even', 'odd') %>">
    <td><%= image_tag_brevet if person.brevet? %></td>
    <td>
      <%= person.name %>
      <% if current_person.administrates? person %><br />
        <span class="person_actions">
          <%= link_to t('Edit'), edit_person_path(person) %>
          <%= link_to t('Delete'), person, method: :delete, data: {confirm: t('people.destroy.confirm', person_name: person.name)} %>
        </span>
      <% elsif current_person == person %><br />
        <span class="person_actions">
          <%= link_to t('Edit'), edit_person_path(person) %>
        </span>
      <% end %>
    </td>
<% if current_person.has_role? 'admin' %>
  <% if current_person.administrates? person %>
  	<td class="shifts"><%= person.shifts.size.to_s %></td>
  	<td><%= person.preferences.to_s %></td>
  <% else %>
    <td></td>
    <td></td>
  <% end %>
<% end %>
    <td class="phone"><%= phone_str(person, delimiter: '<br />') %></td>
    <td><%= render( partial: 'address_link_if_complete', locals: { person: person }, title: t('people.show_map') )%></td>
  </tr>
<% end %>
</table>

app/views/people/new.html.erb
<% content_for :title, @title = t('people.create.title') %>

<p><%= render( partial: 'person_form', locals: { person: @person } )%></p>