config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # See how all your routes lay out with "bin/rails routes" or in the browser at "/routes".

  root to: 'welcome#index'
  get '/home' => 'weeks#index', as: 'home'

  resources :weeks, shallow: true do
    member do
      post 'enable'
      post 'disable'
      get 'render_week_plan'
    end

    resources :days do
      resources :shifts
    end
  end

  resources :shifts
  get 'my_shifts' => 'shifts#my_shifts'

  resources :shiftinfos

  resources :people do
    member do
      get 'find_location'
    end
  end

  get    '/signup' => 'people#new',       as: 'signup'
  get    '/login'  => 'sessions#new',     as: 'login'
  post   '/login'  => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  get '/help' => 'help#contact', as: 'help'

  namespace :tasks, path: 'sudo', as: nil do
    post 'cachesweep'
  end

end

app/models/shiftinfo.rb
class Shiftinfo < ApplicationRecord

  belongs_to :saison
  has_many :shifts

  scope :for_week_and_saison, ->(week, saison){ where(saison_id: saison, id: Shift.where(day_id: week.days).uniq.pluck(:shiftinfo_id)) }

  validates :description, :begin, :end, presence: true

  def begin_plus_offset
    [read_attribute(:begin), read_attribute(:offset)].compact.sum(&:seconds_since_midnight)
  end
  def end_plus_offset
    [read_attribute(:end  ), read_attribute(:offset)].compact.sum(&:seconds_since_midnight)
  end

  def times_str
    "#{self.begin&.strftime( '%H:%M' )} - #{self.end&.strftime( '%H:%M' )}"
  end

  def self.list(cond = {})
    Shiftinfo.includes(:saison).where(cond).collect{|si| "%2d: %12s, %s  %s"% [si.id, si.description, si.times_str, si.saison.name]}
  end

end

app/controllers/shiftinfos_controller.rb
class ShiftinfosController < ApplicationController

  before_action do |c| c.restrict_access 'admin' end

  # GET /shiftinfos
  # GET /shiftinfos.xml
  def index
    @shiftinfos = Saison.shiftinfos_by_saison

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @shiftinfos }
    end
  end

  # GET /shiftinfos/new
  # GET /shiftinfos/new.xml
  def new
    @shiftinfo = Shiftinfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @shiftinfo }
    end
  end

  # POST /shiftinfos
  # POST /shiftinfos.xml
  def create
    @shiftinfo = Shiftinfo.new(shiftinfo_params)
    if current_person.is_admin_for_what.size == 1
      @shiftinfo.saison = current_person.is_admin_for_what.first
    else
      # TODO: add shiftinfo to user-defined saison
    end

    respond_to do |format|
      if @shiftinfo.save
        flash[:notice] = t'shiftinfos.create.success'
        format.html { redirect_to shiftinfos_path }
        format.xml  { render xml: @shiftinfo, status: :created, location: @shiftinfo }
      else
        format.html { render action: "new" }
        format.xml  { render xml: @shiftinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /shiftinfos/1
  # GET /shiftinfos/1.xml
  def show
    @shiftinfo = Shiftinfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @shiftinfo }
    end
  end

  # GET /shiftinfos/1/edit
  def edit
    @shiftinfo = Shiftinfo.find(params[:id])
  end

  # PUT /shiftinfos/1
  # PUT /shiftinfos/1.xml
  def update
    @shiftinfo = Shiftinfo.find(params[:id])

    respond_to do |format|
      if @shiftinfo.update(shiftinfo_params)
        flash[:notice] = t'shiftinfos.update.success'
        format.html { redirect_to shiftinfos_path }
        format.xml  { head :ok }
      else
        format.html { render action: "edit" }
        format.xml  { render xml: @shiftinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shiftinfos/1
  # DELETE /shiftinfos/1.xml
  def destroy
    @shiftinfo = Shiftinfo.find(params[:id])
    @shiftinfo.destroy

    respond_to do |format|
      format.html { redirect_to shiftinfos_path }
      format.xml  { head :ok }
    end
  end


  private

  def shiftinfo_params
    params.require(:shiftinfo).permit!
  end

end

app/helpers/shiftinfos_helper.rb
module ShiftinfosHelper

  def full_descr( shiftinfo, format = '%s (%s)' )
    (format % [h(shiftinfo.description), shiftinfo.times_str]).html_safe
  end

  def shiftinfo_select_label( shiftinfo )
    full_descr( shiftinfo, '%s, %s')
  end

end

app/views/shiftinfos/edit.html.erb
<% content_for :title, @title = t('shiftinfos.edit.title', description: full_descr(@shiftinfo)) %>
<% content_for :navigation_links do %>
  <%= navigation_link t('shiftinfos.index.title') , shiftinfos_path %>
<% end %>


<%= render( 'shared/error_messages', obj: @shiftinfo ) %>

<%= form_with model: @shiftinfo do |f| %>
  <p>
    <b><%=t 'shiftinfo.attributes.description' %></b><br />
    <%= f.text_field :description %>
  </p>

  <p>
    <b><%=t 'shiftinfo.attributes.begin' %></b><br />
    <%= f.text_field :begin, value: @shiftinfo.begin && I18n.l(@shiftinfo.begin, format: :time) %>
  </p>

  <p>
    <b><%=t 'shiftinfo.attributes.end' %></b><br />
    <%= f.text_field :end, value: @shiftinfo.end && I18n.l(@shiftinfo.end, format: :time) %>
  </p>

  <p>
    <b><%=t 'shiftinfo.attributes.offset' %></b><br />
    <%= f.text_field :offset, value: @shiftinfo.offset && I18n.l(@shiftinfo.offset, format: :time) %>
  </p>

  <% if current_person.is_admin_for_what.size > 1 %><p>
    <b><%=t 'shiftinfo.attributes.saison' %></b><br />
    <%= f.select( :saison_id, current_person.is_admin_for_what.sort.collect { |saison|
          [ t("saisons.#{saison.name}"), saison.id ]
        } ) %>
  </p><% end %>

  <p>
    <%= f.submit t'Save' %>
  </p>
<% end %>

app/views/shiftinfos/index.html.erb
<% content_for :title, @title = t('shiftinfos.index.title') %>


<% for saison in Saison.all %>
  <h2><%=t "saisons.#{saison.name}" %></h2>
  <% if saison.shiftinfos.any? %>
    <table>
      <tr>
        <th><%=t 'shiftinfo.attributes.description' %></th>
        <th><%=t 'shiftinfos.index.time_span' %></th>
      </tr>
      <% for shiftinfo in @shiftinfos[saison.name] %>
        <tr>
          <td><%= shiftinfo.description %></td>
          <td><%= shiftinfo.times_str %></td>
          <%= tag.td(link_to( t('Edit'), edit_shiftinfo_path(shiftinfo) ) ) if current_person.is_admin_for? saison %>
        </tr>
      <% end %>
      <% if current_person.is_admin_for? saison %>
      <tr>
        <td colspan="3"><%= link_to(t('shiftinfos.new.title'), new_shiftinfo_path) %></td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p><%=t 'shiftinfos.index.none' %></p>
  <% end %>
<% end %>

app/views/shiftinfos/new.html.erb
<% content_for :title, @title = t('shiftinfos.new.title') %>
<% content_for :navigation_links do %>
  <%= navigation_link t('shiftinfos.index.title') , shiftinfos_path %>
<% end %>


<%= render( 'shared/error_messages', obj: @shiftinfo ) %>

<%= form_with model: @shiftinfo do |f| %>
  <p>
    <b><%=t 'shiftinfo.attributes.description' %></b><br />
    <%= f.text_field :description %>
  </p>

  <p>
    <b><%=t 'shiftinfo.attributes.begin' %></b><br />
    <%= f.text_field :begin %>
  </p>

  <p>
    <b><%=t 'shiftinfo.attributes.end' %></b><br />
    <%= f.text_field :end %>
  </p>

  <p>
    <b><%=t 'shiftinfo.attributes.offset' %></b><br />
    <%= f.text_field :offset %>
  </p>

  <p>
    <b><%=t 'shiftinfo.attributes.saison' %></b><br />
    <% if current_person.is_admin_for_what.size > 1 %>
      <%= f.select( :saison_id, current_person.is_admin_for_what.sort.collect { |saison|
          [ t("saisons.#{saison.name}"), saison.id ]
        } ) %>
    <% else %>
      <%= t("saisons.#{current_person.is_admin_for_what.first.name}") %>
    <% end %>
  </p>

  <p>
    <%= f.submit t'Save' %>
  </p>
<% end %>

app/views/shiftinfos/show.html.erb
<% content_for :title, @title = t('shiftinfos.show.title', description: full_descr(@shiftinfo)) %>
<% content_for :dynamic_links_for_admin do %>
	<%= navigation_link t('shiftinfos.edit.title', description: "") , edit_shiftinfo_path(@shiftinfo) %>
	<%= navigation_link t('shiftinfos.new.title') , new_shiftinfo_path %>
	<%= navigation_link t('shiftinfos.index.title') , shiftinfos_path %>
<% end %>


<p>
  <b><%=t 'shiftinfo.description' %>:</b>
  <%= @shiftinfo.description %>
</p>

<p>
  <b><%=t 'shiftinfo.begin' %>:</b>
  <%= @shiftinfo.begin.strftime( '%H:%M' ) %>
</p>

<p>
  <b><%=t 'shiftinfo.end' %>:</b>
  <%= @shiftinfo.end.strftime( '%H:%M' ) %>
</p>