config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # See how all your routes lay out with "bin/rails routes" or in the browser at "/routes".

  root to: 'welcome#index'
  get '/home' => 'weeks#index', as: 'home'

  resources :weeks, shallow: true do
    member do
      post 'enable'
      post 'disable'
      get 'render_week_plan'
    end

    resources :days do
      resources :shifts
    end
  end

  resources :shifts
  get 'my_shifts' => 'shifts#my_shifts'

  resources :shiftinfos

  resources :people do
    member do
      get 'find_location'
    end
  end

  get    '/signup' => 'people#new',       as: 'signup'
  get    '/login'  => 'sessions#new',     as: 'login'
  post   '/login'  => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  get '/help' => 'help#contact', as: 'help'

  namespace :tasks, path: 'sudo', as: nil do
    post 'cachesweep'
  end

end

app/views/layouts/_banner.html.erb
<div id="banner" class="noprint">
  <%= image_tag("badilogo_s.png", alt: "Logo" ) %>
  <h1>Badi Fraubrunnen</h1>
</div>

app/views/layouts/_bottom_navi.html.erb
<% if logged_in? %>
  <ul id="bottom_navi" class="actions noprint">
    <%= render partial: 'layouts/navigation_in_saison' %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer" class="noprint">
  <p>
  	<a href="https://jigsaw.w3.org/css-validator/">
        <img style="border:0; width:44px; height:16px;"
            src="https://jigsaw.w3.org/css-validator/images/vcss"
            alt="CSS ist valid!" />
    </a>
    Badi2010 © 2008-2019 by Raffael Krebs
  </p>
</div>

app/views/layouts/_main.html.erb
<div id="main">

  <% if content_for? :additional_formats %>
  <div id="links_to_additional_formats" style="float: right;">
    <% for format in content_for(:additional_formats).split(',') do %>
      <%= link_to format.upcase, request.query_parameters.merge(format: format) %>
    <% end %>
  </div>
  <% end %>

  <% if content_for? :title %>
  <h1 id="page_title" class="noprint"><%= content_for(:title) %></h1>
  <% end %>

	<% flash.each do |level, message| %>
	  <%= tag.div(message, class: "flash", id: "flash_#{level}") -%>
	<% end %>
	
	<div id="main_content"><%= yield %></div>

  <%= render( partial: 'layouts/bottom_navi' ) -%>
</div>

app/views/layouts/_member_navigation.html.erb
<% content_for :static_links_for_admin do %>
  <%= navigation_link_unless_current t('shifts.index.title'), shifts_path %>
  <%= navigation_link_unless_current t('shiftinfos.index.title'), shiftinfos_path %>
<% end %>
<% content_for :static_links_for_staff do %>
  <%= navigation_link_unless_current t('people.index.title'), people_path %>
<% end %>
<% content_for :static_links_for_webmaster do %>
<% end %>


<ul>
  <%= navigation_link_unless_current( t('weeks.index.title'), weeks_path )%>
  <%= yield :navigation %>
</ul>

<%= render :partial => 'layouts/role_specific_navigation',
           :collection => %w"staff admin webmaster", :as => :rolename %>

<h3><%=h current_person.name %></h3>
<ul>
  <%= navigation_link_unless_current( t('people.edit.title.staff'), edit_person_path(current_person) )%>
  <%= navigation_link_unless_current( t('shifts.myshifts.title'), myshifts_path )%>
  <%= navigation_link( t('sessions.logout'), logout_path )%>
</ul>

app/views/layouts/_navigation_for_members.html.erb
<% content_for :static_navigation_links do %>
  <%= navigation_link_unless_current t('weeks.index.title'), weeks_path %>
  <%= navigation_link_unless_current t('people.index.title'), people_path %>
<% end %>
<% content_for :static_links_for_admin do %>
  <%= navigation_link_unless_current t('shifts.index.title'), shifts_path %>
  <%= navigation_link_unless_current t('shiftinfos.index.title'), shiftinfos_path %>
<% end %>
<%# content_for :static_links_for_staff do %>
<%# end %>
<%# content_for :static_links_for_webmaster do %>
<%# end %>

<ul><%= render partial: 'layouts/navigation_in_saison' %></ul>

<%= render partial: 'layouts/navigation_for_role',
           collection: %w"staff admin webmaster", as: :rolename %>

<h3><%= current_person.name %></h3>
<ul>
  <%= navigation_link_unless_current( t('people.edit.title.staff'), edit_person_path(current_person) )%>
  <%= navigation_link_unless_current( t('shifts.my_shifts.title'), my_shifts_path )%>
  <%= navigation_link( t('sessions.logout'), logout_path, method: :delete )%>
</ul>

app/views/layouts/_navigation_for_role.html.erb
<% if current_person.has_role? rolename %>
  <% if content_for?(:"static_links_for_#{rolename}") or content_for?(:"dynamic_links_for_#{rolename}") %>
    <h3><%=t "role.#{rolename}" %></h3>
    <ul id="links_for_<%=rolename%>">
      <%= content_for  :"static_links_for_#{rolename}" %>
      <%= content_for :"dynamic_links_for_#{rolename}" %>
    </ul>
  <% end %>
<% end %>

app/views/layouts/_navigation_in_saison.html.erb
<%= content_for :static_navigation_links %>
<%= content_for :navigation_links %>

app/views/layouts/_sidebar.html.erb
<div id="side" class="noprint">
  <% unless Rails.env == 'production' %>
    <p style="margin: 1em 0; font-size: large; color: white;"><%= Rails.env.upcase %></p>
  <% end %>

  <h3><%=t 'navigation' %></h3>
  <% if logged_in? %>
    <%= render partial: 'layouts/navigation_for_members' %>
  <% else %>
    <ul>
      <%= navigation_link_unless_current( t('sessions.login'), login_path )%>
    </ul>
  <% end %>

  <h3><%=t 'help.title' %></h3>
  <ul>
    <%= navigation_link_unless_current( t('help.contact.title'), help_path )%>
  </ul>

  <h3><%=t 'external_links.title' %></h3>
  <ul>
    <li><a href="https://meteo.search.ch/fraubrunnen"><%=t 'external_links.meteo' %></a></li>
    <li><a href="http://www.fraubrunnen.ch/de/kulturfreizeit/schwimmbad/."><%=t 'external_links.official' %></a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <link rel="shortcut icon" href="/favicon.ico" />
  <title><%= "Badi2010 - " + (content_for?(:title) ? content_for(:title) : controller.action_name) %></title>
  <%= stylesheet_link_tag 'application', media: :all %>
  <%# The javascript include tag is at the bottom of the page to improve user experienced load speed. %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container" style="position: relative;">
	<!-- these are composed using css -->
	<%= render( partial: 'layouts/banner'  )%>
	<%= render( partial: 'layouts/sidebar' )%>
	<%= render( partial: 'layouts/main'    )%>
	<%= render( partial: 'layouts/footer'  )%>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/popup.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title><%= "Badi2010 - " + (content_for?(:title) ? content_for(:title) : controller.action_name) %></title>
  <%= stylesheet_link_tag( 'badihomepage' )%>
  <%= stylesheet_link_tag( 'badihomepage', media: :print )%>
</head>
<body>

<!-- renders only the given template -->
<%= yield %>

</body>
</html>